In [1]:
nl=[]
for x in range(2000, 3200):
    if (x%7==0) and (x%5==0):
        nl.append(str(x))
print (','.join(nl))

2030,2065,2100,2135,2170,2205,2240,2275,2310,2345,2380,2415,2450,2485,2520,2555,2590,2625,2660,2695,2730,2765,2800,2835,2870,2905,2940,2975,3010,3045,3080,3115,3150,3185


In [2]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
n=int(input("Input a number to compute the factiorial : "))
print(factorial(n))


Input a number to compute the factiorial : 5
120


In [3]:
number = int(input("Type a number: "))

numberDict = {}
for i in range(1, number+1):
    numberDict[i] = i*i

print(numberDict)

Type a number: 6
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36}


In [4]:
def remove_char(str, n):
      first_part = str[:n] 
      last_part = str[n+1:]
      return first_part + last_part
print(remove_char('Python', 0))
print(remove_char('Python', 3))
print(remove_char('Python', 5))

ython
Pyton
Pytho


In [5]:
import numpy as np
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [6]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("Original array1:")
print(x)
print("Original array1:")
print(y)
print("Covariance matrix of the said arrays:\n",np.cov(x, y))

Original array1:
[0 1 2]
Original array1:
[2 1 0]
Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [7]:
import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list)


Provide D: 5
[4]
